### ISSUE TITLE
Config.MaxErrors defaults to no retry

### ISSUE THREAD

**Issue by ljdelight** [davidnewhall/unifi-poller#123]
I'm running unifi-poller in a docker container and the process terminated due to a maximum error count of 0. There should be a better default for `Config.MaxErrors` (in `config.go`) so that the process can handle some controller downtime.

```
2019/09/24 03:12:51 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf                                                                                                              
2019/09/24 03:12:51 [INFO] UniFi Poller v1.5.3-418 Starting Up! PID: 1                                                                                                                        
2019/09/24 03:12:51 [INFO] Found 1 site(s) on controller: default (Default)                                                                                                                   
2019/09/24 03:12:51 [INFO] Polling UniFi Controller at https://10.10.0.9:8443 v5.10.26 as user influx. Sites: [all]                                                                           
2019/09/24 03:12:51 [INFO] Logging Measurements to InfluxDB at http://dockerplay:8086 as user unifi                                                                                           
2019/09/24 03:12:51 [INFO] Everything checks out! Poller started, interval: 30s                                                                                                               
2019/09/24 03:13:22 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 26, Wireless APs: 0, Gateways: 1, Switches: 0, Points: 37, Fields: 1615
...
2019/09/24 04:03:51 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 27, Wireless APs: 0, Gateways: 1, Switches: 0, Points: 38, Fields: 1664
2019/09/24 04:04:21 [ERROR] (1/0) unifi.GetSites(): Get https://10.10.0.9:8443/api/stat/sites: dial tcp 10.10.0.9:8443: connect: connection refused
2019/09/24 04:04:21 [INFO] UniFi Measurements Recorded. Sites: 0, Clients: 0, Wireless APs: 0, Gateways: 0, Switches: 0, Points: 0, Fields: 0
2019/09/24 04:04:21 [ERROR] reached maximum error count, stopping poller (1 > 0)
```
Great job on the clear logging and exiting with an error status.

**Comment by davidnewhall** [comment]
Hello! Thank you for writing in!

The max errors default being zero is actually the most sane default possible. The problem is that when the controller comes back up the authentication cookie stored in the poller is invalid. You want it to exit, so it can re-authenticate and get a new cookie. This happens when Docker starts it back up. The old behavior (before I added max errors logic) was to never exit, and this lead to long periods of time where no data was collected. The recommendation is to set the `restart` Docker parameter to `always`; this will ensure the best possible experience with the poller. Good luck!

**Comment by ljdelight** [comment]
I'm comparing the logs and I see that the unifi-poller got the `connection refused` due to the controller upgrading (not from an expired cookie). 

It looks like when there are various networking issues (reboots, timeouts, etc) the poller does not work so well given unifi takes time to startup, resulting in lots of tcp `connection refused` and possibly terminated permanently by hitting max restart attempts held by docker, systemd. kubernetes will see a lot of churn, but has a restart policy of `always` with an exponential backoff limited at 5 minutes (plenty of time for the controller to start back up).

So in the case of a controller upgrade the default of no retries is unfortunate. Spit balling a retry approach: If the failure is from an invalid cookie it will re-auth and collect immediately, otherwise sleep and retry until a default of, say, 4 failures (4*30sec=2min). 

What do you think?

--------
Just for reference, here are logs for reference showing the upgrade.
From my previous post

    Polling UniFi Controller at https://10.10.0.9:8443 v5.10.26"

and the unifi logs below along with the unifi-poller now shows v5.11.46:

    Polling UniFi Controller at https://10.10.0.9:8443 v5.11.46


Unifi controller log around the time of update:
```
[2019-09-23T22:12:51,074] <webapi-240> INFO  event  - [event] Admin[influx] log in from 10.10.0.87
...
[2019-09-23T23:04:51,453] <localhost-startStop-1> INFO  system - ======================================================================
[2019-09-23T23:04:51,459] <localhost-startStop-1> INFO  system - UniFi 5.11.46 (build atag_5.11.46_12723 - release/release) is started
[2019-09-23T23:04:51,460] <localhost-startStop-1> INFO  system - ======================================================================
[2019-09-23T23:04:51,460] <localhost-startStop-1> INFO  system - BASE dir:/usr/lib/unifi
[2019-09-23T23:04:51,526] <localhost-startStop-1> INFO  system - Current System IP: 10.10.0.9
[2019-09-23T23:04:51,527] <localhost-startStop-1> INFO  system - Hostname: unifi
```

**Comment by davidnewhall** [comment]
You have correctly deduced the behavior of the application. Any error will cause it to exit. I could probably write code to keep it running and just keep trying to re-authenticate, but that code is not there now. It only authenticates once, and if you restart the controller that authentication is no longer going to work. The easiest thing to do is set your system up to restart the application when it stops. 

The Linux packages available use a systemd service unit that makes sure the application restarts when it exits. The home-brew install uses a launch daemon config to achieve the same state. Neither of these have max restart attempts get invoked in normal operation. All I can do for Docker users is provide recommendations. 

The following issues were opened because the poller did not exit (or properly restart) when it had an error. There may have been a couple others too. 
https://github.com/davidnewhall/unifi-poller/issues/116
https://github.com/davidnewhall/unifi-poller/issues/108
https://github.com/davidnewhall/unifi-poller/issues/93
https://github.com/davidnewhall/unifi-poller/issues/78

Also, I'd totally argue that these two scenarios (failed auth and connection refused) are ultimately going to lead to the same thing. If you get a connection refused from your controller, any cookie you had when it was working will not work again.
> I'm comparing the logs and I see that the unifi-poller got the connection refused due to the controller upgrading (not from an expired cookie).

But they could be different if you used a proxy in the middle. That would be pretty advanced; most people have this on the same network, and in some cases, the same server or cloudkey.

Hope this makes sense!

**Comment by davidnewhall** [comment]
The referenced pull request has more meta data around the max errors option and the decision to make poller exit when it encounters an error.

It sounded like you have it figured out, but .... If you need assistance getting Docker or Kubernetes to restart the poller correctly (after a few minutes because it usually takes the controller a few minutes to restart/upgrade), let me know! Or jump into the Discord. We can certainly provide some additional operational guidance!
