### ISSUE TITLE
Script not executing in cloudkey

### ISSUE THREAD

**Issue by vijaytejak** [davidnewhall/unifi-poller#138]
I am trying to execute the scrip in cloud controller, following is the error i got
![image](https://user-images.githubusercontent.com/14872281/68541454-b8ace280-03c5-11ea-9d0d-5494908cae38.png)

**Comment by davidnewhall** [comment]
The script is designed for Linux servers not integrated systems like a cloudkey.

To run this on a cloudkey, you'll need to use a Docker image. Unfortunately I have very little experience doing this because I do not own a cloudkey. There is a gentleman on the Discord that has installed this on on ckg2+ - his name is `Maxwell#6651` - and he may not be the only one. Discord is probably a good place to start to get assistance putting this directly on the CloudKey. Good luck!

**Comment by davidnewhall** [comment]
Unfortunately, I've learned that Maxwell is no longer in the Ubiquiti Discord. I was unable to find anyone else who has done this. :(

**Comment by davidnewhall** [comment]
I wish I could do more for you here, but I don't have any experience setting this software up on a CloudKey. If you get it working, please let me know so we can setup a wiki for others! Good luck!
