### ISSUE TITLE
Change site ID

### ISSUE THREAD

**Issue by zunder1990** [davidnewhall/unifi-poller#16]
My controller has many sites, in default setup of the poller it polls stats from my default site but I want to change it.  I tried to change the unifi url to add the site ID but I got the below error. 

```
2019/04/09 15:21:49 Authenticated to Unifi Controller @ https://192.168.1.7:8443/manage/site/v3p6dxbq/ as user xxxx
Logging Unifi Metrics to InfluXDB @ http://192.168.1.11:8086 as user unifi
Polling Unifi Controller, interval: 30s
[INFO] Everyting checks out! Beginning Poller Routine.
[ERROR] uni.GetClients(): json.Unmarshal([]UCL): invalid character '<' looking for beginning of value

```

**Comment by davidnewhall** [comment]
Thank you for your report!

I think if you turn on Debug mode (add `-D` to cli args) it will output the whole response. That error indicates it's receiving html instead of json. Make sure you run `make deps` or `dep ensure -update` to get the latest [unifi](https://github.com/golift/unifi/releases/tag/v1.0.1) library release. This should at least give you a few more clues as to why the URL you're trying did not work. You may be onto something there, but I'm just not sure how multi-site works yet.

I'll need some time to look into this. I have some things tying me up right now, but I should be able to find a way to allow multi-site. I only have one site to work with, but I'll try to find the right pieces to make it work, and I may request your help. Your JSON output may be useful, I'll let you know! 

Regards,
-david

**Comment by zunder1990** [comment]
Yes I change the URL to try to get SITEID to work but when url was changed back to default it worked on polling the SITEID of "default"  

There needs to be support for changing of the SITEID for people with more than one site on a controller.

**Comment by davidnewhall** [comment]
Hello, I've looked into this just briefly. There is going to be a considerable amount of work/rewrite of methods to support multiple sites. The `default` site is currently hard coded in the unifi library here: https://github.com/golift/unifi/blob/master/unidev.go#L15-L26 - Now I definitely want this library to support multiple sites, and in an elegant way. What I imagine I'll do is provide an input list to specify which sites you want to poll and include; likely with an `all` selector. I hope to have something for you to try within a couple weeks.

**Comment by davidnewhall** [comment]
I've added a number of new features, including better dashboards, to handle controllers with multiple sites. Please consider upgrading and giving it a go!
