### ISSUE TITLE
Controller with multiple sites

### ISSUE THREAD

**Issue by mmccollum2** [davidnewhall/unifi-poller#26]
Hey @davidnewhall I've been working on this for a bit and while using Ubuntu 18.04.2

- I noticed that your installation guide first started running as a normal user when installing go/deps/ronn and then went sudo make install which errors out because go variables were not setup for root. When doing this install from linux, if you prep the guide to start as root then it should be fine.

Here's a quick set of lines for influxdb install for 18.04.2 that work great for your guide

```
echo "deb https://repos.influxdata.com/ubuntu bionic stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
sudo curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
sudo apt -y update
sudo apt install -y influxdb

influx
CREATE DATABASE unifi
CREATE USER unifi WITH PASSWORD 'unifi' WITH ALL PRIVILEGES
GRANT ALL ON unifi TO unifi
```

Like Issue "Change site ID #16" - We also have multiple sites and although I've tried 
`sites = ["sitename1"]`

The only thing that is currently working would be all sites, and then it just absolutely pulls in everything haha. Trying to see if I can restructure the data with your poller to have Grafana dashboards broken down by sites, which would be incredible, and the Unifi community would go bananas. So far you're doing an awesome job, let me know If I can help or work on it with you?

 (I don't use GitHub very much, so I apologize for not reporting this comment properly!)

**Comment by davidnewhall** [comment]
This is all great feedback. Thank you.

Things I'm working on:
- I'm moving away from `make install` and packages for your OS are now provided on the releases page. Future releases will exclude `install` from the `Makefile`. 
- I'll add a section in the wiki for installing InfluxDB.

I've not been able to test this code with a controller that has more than 1 site. I'm glad it works with at least `all`, but it should allow you to pick specific sites. What happens when you change the list to `["sitename1"]` and fire up the app?  If you enable debug mode, does anything more useful come out?

As for breaking the dashboard down by site: You can add a variable to the dashboard for the site names and use that. I'll look into updating my templates with this new feature.

If you'd like to help out, please test the new package(s). I could use some feedback on how those work out for others. If you're familiar with Go, I could use assistance figuring out why specifying a site is not working. As I mentioned, I only have 1, so debugging this is complicated. (I may need to just figure out how to add another one)

Please don't apologize for helping!

Regards,
-david

**Comment by mmccollum2** [comment]
Hey David,

Sounds good, I'm working with a Unifi controller hosted in the cloud with 12 sites, so lots to play with. I'm also working with snapshots so I can move back and forth between configurations to easily test different code, unfortunately, I'm new to go, but I'm getting used to it. i'll test out the package deployment to see how it goes too!

When I specified anything but all in the sites, the poller said everything looked great, but it wouldn't pull any data and would think there were 0 sites and 0 of any devices, I tried different sites, case sensitive, no quotes, few different things. Good idea, I'll try to debug and see if I get anything else.

Yes, I took some time for lunch to think about how I could manipulate these dashboards and then I could take the same influxdb data and just reference it based on the site name and pull devices and data from only those sites.

As for your influxdb post, just one thing that I noticed, that apt install code is specific to 
**"ubuntu bionic stable"** so you'll want to note that it's meant for "18.04.2 LTS (Bionic Beaver)"

Wooohooo, chat soon!

**Comment by mmccollum2** [comment]
And just like the InfluxDB install code, here's what is needed for Grafana.
(This will set it up on localhost:3000 with admin/admin login)

##################### Quick Grafana Install for Ubuntu 18.04.2#######################
curl https://packages.grafana.com/gpg.key | sudo apt-key add -
sudo apt-get install -y apt-transport-https
sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"

sudo apt -y update && sudo apt -y install grafana
systemctl daemon-reload
systemctl start grafana-server
sudo systemctl enable grafana-server.service
systemctl status grafana-server

**Comment by davidnewhall** [comment]
I've managed to alert the dashboard to include the site names, but it also requires an update to the `unifi` library to work. I'll release a new version with these updates soon. Still trying to figure out why you cannot poll specific sites.

Thanks for the grafana code and influx note. I'll update the wiki some more.

**Comment by davidnewhall** [comment]
**Now**
I did not find the bug causing the issue you're having with loading specific sites. I wonder if it's possible you're entering the wrong name?  When you use `["all"]` and `debug` mode the application should output a line of text with all the site names; it looks like this:
```
2019/06/05 18:33:56.550377 types.go:36: [DEBUG] Found 1 sites: default
```
Be sure to use the names you see in this list as the names in the `sites` config list. I do not believe they can have spaces, but I could be wrong. Waiting for your results on this "test."

**Later**
I've identified a critical bug that prompts me to hurry out a release. I will have one tonight that has some new site_name features that work the dashboards I'm updating. Please check back later tonight or tomorrow for a new release. Install it, preferably using one of the travis-ci built packages (attached to the release on the Releases page). Be sure to backup your `up.conf` file and `sudo make uninstall` before you install the package. Import the 3 new dashboards and let me know how things work out. You should be able to see data for each site individually.

**Comment by davidnewhall** [comment]
The new dashboards are in this branch: https://github.com/davidnewhall/unifi-poller/tree/dn2_dashboards/examples (also a PR @ #27). Feel free to download them and try them out. I'm cutting the new release now. The dashboards do not need to be merged before hand. I'm waiting for more data in my local grafana so I can attach updated screenshots. I dropped my influx db so things looks rather bare at the moment.

**Comment by mmccollum2** [comment]
I'm having some fun with this now, getting productive!

thanks for the update, I rebuilt with the new package and got it back up and running, found the issue with putting the site name into the up.conf - see pic as it requires you to put the ID of the site? Or i'm guessing it's the ID of the site, anyways, it worked when i put one of those id's in up.conf (As I can change the "sitename" in the controller to whatever I want, and the poller will still be able to connect to it. (Do you know if there's a way to output the site id of a site?)
![sites](https://user-images.githubusercontent.com/13972038/59062087-3e01f900-8862-11e9-8aff-c53e630bffd2.png)


Also, on your new dashboard updates, you mentioned that a few plugins are required, two of them already come with grafana - Assuming you're using updated. 6.2.2. otherwise might as well put these links in there for people that want to be able to install them.

clock grafana-cli plugins install grafana-clock-panel
discrete grafana-cli plugins install natel-discrete-panel
SingleStat and Table -  These plugins are included with Grafana and does not require installation. Woo.

Adding your new dashboards now for testing, I'm new to json for grafana so seeing how I can manipulate it. I'd be very interested on working with you to restructure the data when it's being polled from the controller so that it resembles a different data structure

Currently

Database_name
     - usg
     - usw
     - uap

Proposed

Database_name
      - Site1
            - uap
            - usg
      - Site2
            - uap
            - usg

I'm going to test out the dashboard json to see if I can select devices with specific site names attached to them, but just tossing the idea out there if you're considering more development for multi-site controllers.

**Comment by mmccollum2** [comment]
- On your updated dashboards, looks like you set the datasource name to Unifi instead of before when importing them there was an option to pick which datasource to use? Interested on if that helped your setup? (I just changed my datasource name to Unifi for this testing)

- Looks like your Unifi Clients dashboard requires this plugin too
`grafana-cli plugins install grafana-piechart-panel
`

**Comment by davidnewhall** [comment]
Glad you found the site IDs! I'm not sure I can change it to use the name because the `default` name can be anything and it'd become a backward incompatible change. What I can do is make the printing of site names not a debug message, and instead, print all the time. I can also include the human name next to the id so you can distinguish them. I think that will help. Thanks for the screenshot, I really had no idea what this looks like for someone else; it's very enlightening. 

I appreciate the info about the plugins. I am aware of a couple of them are standard, and I just wanted to call it out anyway. I'll add the piechat reference, thanks!

Restructuring the data as you've proposed is a backward incompatible change. I'm hopeful the `Site` menu on the new dashboard provides the same level of functionality you need. I'll also point out the current structure is:
```
Database_name
     - usg
     - usg_networks
     - usw
     - usw_ports (next update)
     - uap
     - uap_radios
```

I'll see if I can figure out how to export the json with a selectable data source. I have an idea, and I can test it better next time!

**How do the dashboards work out?** Specifically around controlling the site.

**Comment by davidnewhall** [comment]
I've cut a new release that cleans up the site names in the Grafana dashboards. I also added more USW support and added a USW dashboard. Check it out if you have Unifi switches. The new release also outputs the site names in the log by default, and throws an error if you specify one that's missing. Please install the new package and let me know how things go. You'll probably want to drop and re-create your unifi influxdb database to get rid of the old-style site names.

skype://davidnewhall2
discord://TwitchCaptain#2728
..or reply here :)

**Comment by davidnewhall** [comment]
I also fixed all the dashboards so you can select the data source.

**Comment by davidnewhall** [comment]
Don't take this issue being closed as a sign I'm not waiting to hear from you! Still looking forward to some updates. I've thrown another round of dashboard updates in master too. Fixed some bugs and aligned things a little better.

**Comment by mmccollum2** [comment]
No worries, thanks for putting so much work into this, i'm looking forward to diving back into it next week. I have a work project for the next few days that has took it's place. Talk soon!
