### ISSUE TITLE
Connection Refused from Unify Controller 5.10.24

### ISSUE THREAD

**Issue by MachinalInstinct** [davidnewhall/unifi-poller#57]
Having Set up my UniFi user as instructed in the installation instructions, triple checked that my username/password combo is correct
![image](https://user-images.githubusercontent.com/34972186/60377882-61fcc880-9a23-11e9-9aea-9fc36ceb522b.png)
![image](https://user-images.githubusercontent.com/34972186/60377902-848ee180-9a23-11e9-9d26-5aee2d1f331a.png)
Connection is refused and no further error is thrown, UniFi server logs don't show anything
![image](https://user-images.githubusercontent.com/34972186/60377907-a2f4dd00-9a23-11e9-9d42-00ea6761df48.png)

**Comment by doc-jay** [comment]
@MachinalInstinct in your 'up.conf' file, just uncomment the 'unifi_url' parameter, should work after that.

Also, in the users in Unifi for the  user I made, I went ahead and check marked 'allow read only access to all sites'.  Helpful if you have more than one site you want to monitor.

**Comment by davidnewhall** [comment]
UniFi Poller is trying to connect to the controller on localhost (127.0.0.1). Unless the controller is running in the same Docker container, that's unlikely to work. I'm not a pro at Docker, but there should be a way to pass in a port from the host (if the controller really is running on the host running docker). Otherwise, you'll want to put the correct url into the `unifi_url` parameter in the config file. Probably whatever you put into your web browser to access it? 

Reply with more details about where your controller is in comparison to the Docker host and I'll give the best guidance I can!

**Comment by MachinalInstinct** [comment]
Thanks @davidnewhall, that was the clue I needed - My controller was running on the same physical hardware but on a different instance and that is why they wouldn't communicate between each other, changed the IP to the allocated subnet ip-s and all works a charm!

**Comment by davidnewhall** [comment]
Rad!!
